### PR TITLE
Audio player functionality completed

### PR DESCRIPTION
**Pull request by Javier-Szyfer**
Completed functionality for the audio player:

- Play/Pause toggle
- Mute Toggle
- Progress bar
- Volume Slider
- Handle playlist queue 
- Prev/Next 
- Continuous listen:  when a track ends the following starts automatically.

Testersss needed. We might be at a good point to export it and try to integrate it on the sandbox.

Note: Making the UI pretty so DO NOT MERGE this branch : )

### CODE REVIEW

**Review by 0xTranqui — APPROVED** [review]
@Javier-Szyfer all this stuff looks great. In terms of testing, do you want to try to get it into the neosound-sandbox so that we can see a live build? Just need to add a new branch to that I believe that consumes the underlying packages and replicates the UI? let me know what would be helpful for you

**Comment by Javier-Szyfer** [comment]
@0xTranqui  yep looking forward to exporting this as a package,  i would like to have @dblodorn CR first and then we are good.
Prob tomorrow will have the sandbox + audio player imported to test things live.

**Review by dblodorn — APPROVED** [review]
This looks and works awesome! Approving for merge and a first publish.
Adding a number of thoughts for follow up work that could get folded in, and then some layout notes following the list.

- [x] Big Feature: Set up a Provider / useProvider hook, wrap al the UI in that
- [ ] Add loading indicator somewhere - perhaps swap out spinner with play pause
- [x] Check breakpoints, need solution for word wrap with title on smaller viewports, extra long titles may need a horizontal scroll.
- [x] Fixed width on time counter so layout does not jump horizontally
- [x] Mobile layout reflow
- [x] Include playlist logic in package
- [x] Export MusicNFT and playlist typing from package
- [ ] Props schema may evolve once we integrate drops contract data
- [ ] Logic for usage of single track vs playlist, or option to render multiple players vs one
- [ ] Toggle between simplified and full featured UI, simple just being like play / pause icon

Mobile, maybe default layer becomes stacked.
Screen Shot 2022-09-25 at 5 29 06 PM

Time counter causes layout to shift horizontally:
Screen Shot 2022-09-25 at 5 29 26 PM

Word wrap / title length handling:
Screen Shot 2022-09-25 at 5 30 05 PM

**Comment by dblodorn** [comment]
@Javier-Szyfer @0xTranqui just realized another important addition would be the addition of selectors so user can target each component from a custom stylesheet. Wouldn't need to attach any styling to them.

We could just establish a general pattern where the universal prefix is: 

`pa-[package-name]__`

ie: `pa-audioplayer__`

Example usage:

```
export const PlayToggle = ({ pausePlayHandler, playing }: PlayToggleProps) => {
  return (
    <>
      <button
        onClick={pausePlayHandler}
        className={`pa-audioplayer__play-button ${!playing ? "inline-block" : "hidden"}`}
      >
        <GrPlayFill className="pa-audioplayer__play-icon w-6 h-6" />
      </button>
      <button
        onClick={pausePlayHandler}
        className={`pa-audioplayer__pause-button ${playing ? "inline-block" : "hidden"}`}
      >
        <GrPauseFill className="pa-audioplayer__pause-icon w-6 h-6" />
      </button>
    </>
  );
};
```

**Comment by Javier-Szyfer** [comment]
@dblodorn  everything on this CR seems accurate, thanks.

**Pull request merged**
